// <auto-generated />
namespace NoteBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20210125 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210125));
        
        string IMigrationMetadata.Id
        {
            get { return "202101250634488_20210125"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
